# Generated by Django 4.1.6 on 2023-05-08 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='duracao_min',
        ),
        migrations.CreateModel(
            name='HistoricoAlunoPre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('numero_aulas', models.IntegerField(blank=True, default='', null=True)),
                ('numero_faltas', models.IntegerField(blank=True, default='', null=True)),
                ('aluno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='academico.aluno')),
                ('turma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='academico.turma')),
            ],
        ),
    ]
