# Generated by Django 4.1.6 on 2023-04-26 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='bairro_de_vola',
            new_name='bairro_de_volta',
        ),
    ]
