# Generated by Django 4.1.6 on 2023-05-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_remove_horario_duracao_min_historicoalunopre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='nome_do_meio',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='ultimo_nome',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='senha',
        ),
        migrations.AddField(
            model_name='horario',
            name='teste',
            field=models.TimeField(default=1),
        ),
        migrations.AlterField(
            model_name='turma',
            name='nivel',
            field=models.CharField(blank=True, choices=[('op beginer I', 'op beginer I'), ('op beginer II', 'op beginer II'), ('op beginer III', 'op beginer III'), ('op intermediate I', 'op intermediate I'), ('op intermediate II', 'op intermediate II'), ('op advanced I', 'op advanced I'), ('op advanced II', 'op advanced II'), ('op advanced III', 'op advanced III'), ('op advanced IV', 'op advanced IV'), ('simbolico', 'simbolico'), ('simbolico intuitivo I', 'simbolico intuitivo I'), ('sensório motor II', 'sensório motor II')], default='', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='HistoricoAlunoPre',
        ),
    ]
